os:
  - linux

dist: bionic

language: c

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install libsox-dev
  - sudo mkdir /usr/include/sox
  - sudo mv /usr/include/sox.h /usr/include/sox/sox.h
  - sudo apt-get install libpulse-dev

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
