os:
  - linux

dist: bionic

language: c

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install libsox-dev
    libpulse-dev
    cppcheck
    libgtk-4-dev
  - sudo mkdir /usr/include/sox
  - sudo mv /usr/include/sox.h /usr/include/sox/sox.h

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - cd .. && sh static_analysis.sh
