os:
  - linux

dist: bionic

language: c

compiler:
  - gcc

before_install:
  - apt-get update

install:
  - apt-get install libsox-dev

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - gcc-9

script:
#   - export CC=gcc-7
  - gcc -v && cmake --version
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
